language: php
php:
  - 7.1

services:
  - postgresql
before_script:
  - cp .env.travis .env
  - psql -c "CREATE DATABASE homestead_test;" -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

deploy:
  - provider: heroku
    api_key:
      secure: MgIV5VpUGUmVWsC4IllbRzbOQoG3AZKml07SIg0U2/e8zQcp87/duG7L2IRJPVnVOuvbZQOJCHOMLU/HSX9EqjiKYO+DxvpwI3NPv4QrFh2BMl/GBbDEwnfwNrBwWvXFnXPzss/iEa1jJrjL+99uJALn12YcPHtsuQQCoW9Mq9xx9lzGtYdzNiuOD79pNexP19elZtBB7ggfTZARjMELSkgKmTdX2DN+yldyCdltMqVHwYCHSeKGnITiZ7k5ya3PoMCUvLkTzMmsgplANLtElT4/iCDkcMNCh3vVIar9VYfgssVrzo5VIOKQtEHhFPj9gOmDQhgq6hCN4xL3KLzNqs0yImkw3ux9KqXsQpM+Y3Zm7OyrPKwbFXZSVHICGW/oUwb2iBV+7K4aZnerdd5hagMIHbjy3XdNkvcPS2XMtC0FKUjckDJxUM6gtnHG3HZHPgvmF/IXxZF3HvwgJUALE4OdwMImVZLzDwaEuvBTtTWJij4fj+czcB0kBxeu31DCwZKzD2l5NIsBdIUZNwF1hE0hFCJWYSEcts7NpQm0HKVMIUJIwAoUgjGFaJq/LIgKGIclSjjbZc6oXCoEkaQptAlDVyjotZRU0WLrJr0+ouUC1FmPwfMPsZM3lAs2XfRKKSa5hrUZLlhC0XhnIEmJnNKkqiuisbXvOfHB+L40C+4=
    app: hidden-depths-47488
    on:
      all_branches: true

